import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import React, { useMemo } from 'react';
import * as github from '@/utils/github';
import { Providers } from './providers';
import { cn } from '@/utils/cn';
import { RibbonApp } from '@/components/common/RibbonApp';
import { backgrounds } from '@/assets/backgrounds';
import { TuiSidebarContent } from '@/components/layout/TuiSidebarContent';
import { TuiNavigationContent } from '@/components/layout/TuiNavigationContent';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const version = process.env.APP_VERSION ?? 'local';

console.log(`%cApp Version:%c${version} (${github.commit(version)})`, 'font-weight: bold;');

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const background = useMemo(() => {
    return backgrounds[Math.floor(Math.random() * backgrounds.length)];
  }, []);

  return (
    <Providers>
      <html lang="en">
        <RibbonApp as="body" style={{ background: '#0d0d0d' }} className={cn(geistSans.variable, geistMono.variable)}>
          <RibbonApp.Background src={background.src} />
          <RibbonApp.Sidebar className="bg-tui-dark">
            <TuiSidebarContent />
          </RibbonApp.Sidebar>
          <RibbonApp.Navigation className="bg-tui-dark">
            <TuiNavigationContent />
          </RibbonApp.Navigation>
          {children}
        </RibbonApp>
      </html>
    </Providers>
  );
}
